apiVersion: v2
name: earth
description: Surfscan Insight Infra Modules - Save test

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "Dev"

dependencies:
  # Insight Global Configuration
  - name: eros
    version: 0.1.0
  # Insight VNI Configmap
  - name: ceres
    version: 0.1.0


# dependencies:
#   # Insight Global Configuration
#   - name: config
#     version: 0.1.0
#     repository: file://../config
#   # Insight VNI Configmap
#   - name: vni-configmap
#     version: 0.1.0
#     repository: file://../vni-configmap
#   # Insight Logger
#   - name: spooler
#     version: 0.1.0
#     repository: file://../spooler
#   # Insight Redis
#   - name: redis
#     version: 0.1.0
#     repository: file://../redis
#   # Insight Node Service Manager
#   - name: nsm
#     version: 0.1.0
#     repository: file://../nsm
#   # Insight Node Data Manager
#   - name: ndm
#     version: 0.1.0
#     repository: file://../ndm
#   # Insight Sequence Manager
#   - name: sequence-manager
#     version: 0.1.0
#     repository: file://../sequence-manager
  
